title: Christoph Eberle # your name (or website title) here
logo: "/images/profile_circ.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/example/">LinkedIn</a>
  <br><br>
  I am pursuing a MSc. degree in Physics at LMU Munich, Germany.
  <br><br>
  My research concerns the reconstruction of time-varying gamma ray flux fields as part of the Information Field Theory group at the Max-Planck Institute for Astrophysics.l
  <br><br>
  Currently I am working as a working student in Data Science & Machine Learning at ray sono with a focus on timeseries analysis and outlier detection.
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
